language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

jobs:
  allow_failures:
    os: osx

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j
  - ctest -j -V
